apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: subdomain-gateway
spec:
  gatewayClassName: cilium
  listeners:
  - protocol: HTTP
    port: 80
    name: http-gw
  - protocol: HTTPS
    name: https-gw
    port: 443