---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "api-secrets"
data:
  ConnectionStrings__default: "{{ .Values.secrets.ConnectionStrings__default | b64enc }}"
  Domain__api__signing_key: "{{ .Values.secrets.Domain__api__signing_key | b64enc }}"
  Domain__resource__signing_key: "{{ .Values.secrets.Domain__resource__signing_key | b64enc }}"
  Domain__pos__signing_key: "{{ .Values.secrets.Domain__pos__signing_key | b64enc }}"
  Domain__master__signing_key: "{{ .Values.secrets.Domain__master__signing_key | b64enc }}"
  Domain__consumer__signing_key: "{{ .Values.secrets.Domain__consumer__signing_key | b64enc }}"
  Domain__ordering__signing_key: "{{ .Values.secrets.Domain__ordering__signing_key | b64enc }}"
