---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "resource-api-config"
  labels:
    app.kubernetes.io/name: "foodsphere-api"
    app.kubernetes.io/component: "resource-api"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.resource_api.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.resource_api.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.resource_api.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.resource_api.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  ASPNETCORE_ENVIRONMENT: "{{ .Values.config.resource_api.ASPNETCORE_ENVIRONMENT }}"