---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "resource-api-service"
  labels:
    app.kubernetes.io/name: "foodsphere-api"
    app.kubernetes.io/component: "resource-api"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "foodsphere-api"
    app.kubernetes.io/component: "resource-api"
    app.kubernetes.io/instance: "{{.Release.Name}}"
  ports:
    - name: "http"
      protocol: "TCP"
      port: {{ .Values.parameters.resource_api.port_http }}
      targetPort: {{ .Values.parameters.resource_api.port_http }}