---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "ordering-api-deployment"
  labels:
    app.kubernetes.io/name: "foodsphere-api"
    app.kubernetes.io/component: "ordering-api"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "foodsphere-api"
        app.kubernetes.io/component: "ordering-api"
        app.kubernetes.io/instance: "{{.Release.Name}}"
    spec:
      containers:
        - image: "{{ .Values.parameters.ordering_api.ordering_api_image }}"
          name: "ordering-api"
          envFrom:
            - configMapRef:
                name: "ordering-api-config"
            - configMapRef:
                name: "api-config"
            - secretRef:
                name: "api-secrets"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: {{ .Values.parameters.ordering_api.port_http }}
            # - name: "https"
            #   protocol: "TCP"
            #   containerPort: {{ .Values.parameters.ordering_api.port_https }}
          imagePullPolicy: "Always"
  selector:
    matchLabels:
      app.kubernetes.io/name: "foodsphere-api"
      app.kubernetes.io/component: "ordering-api"
      app.kubernetes.io/instance: "{{.Release.Name}}"
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
