---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "ordering-api-service"
  labels:
    app.kubernetes.io/name: "foodsphere-api"
    app.kubernetes.io/component: "ordering-api"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "foodsphere-api"
    app.kubernetes.io/component: "ordering-api"
    app.kubernetes.io/instance: "{{.Release.Name}}"
  ports:
    - name: "http"
      protocol: "TCP"
      port: {{ .Values.parameters.ordering_api.port_http }}
      targetPort: {{ .Values.parameters.ordering_api.port_http }}
    # - name: "https"
    #   protocol: "TCP"
    #   port: {{ .Values.parameters.ordering_api.port_https }}
    #   targetPort: {{ .Values.parameters.ordering_api.port_https }}
