---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "pos-api-deployment"
  labels:
    app.kubernetes.io/name: "foodsphere-api"
    app.kubernetes.io/component: "pos-api"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "foodsphere-api"
        app.kubernetes.io/component: "pos-api"
        app.kubernetes.io/instance: "{{.Release.Name}}"
    spec:
      containers:
        - image: "{{ .Values.parameters.pos_api.pos_api_image }}"
          name: "pos-api"
          envFrom:
            - configMapRef:
                name: "pos-api-config"
            - configMapRef:
                name: "api-config"
            - secretRef:
                name: "api-secrets"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: {{ .Values.parameters.pos_api.port_http }}
          imagePullPolicy: "Always"
  selector:
    matchLabels:
      app.kubernetes.io/name: "foodsphere-api"
      app.kubernetes.io/component: "pos-api"
      app.kubernetes.io/instance: "{{.Release.Name}}"
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
